# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'airsense-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
  - job_name: 'airsense-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    
  - job_name: 'airsense-redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    
  - job_name: 'airsense-kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']